# Generated by Django 2.1.1 on 2018-09-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_physiotherapist',
            field=models.BooleanField(default=False),
        ),
    ]
