# Generated by Django 2.1.1 on 2018-09-26 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_user_is_physiotherapist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_physiotherapist',
        ),
    ]
